steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/catclawboard-server', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/catclawboard-server']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'catclawboard-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/catclawboard-server'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:catclawboard-db'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=$PROJECT_ID:us-central1:catclawboard-db,DB_USER=root,DB_PASS=yz188188,DB_NAME=catclawboard,JWT_SECRET=catclaw-jwt-s3cret-k3y-2026,ADMIN_USERNAME=admin,ADMIN_PASSWORD=yz188188'
images:
  - 'gcr.io/$PROJECT_ID/catclawboard-server'
